apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-app.fullname" . }}-config
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.app.env | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
