apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app.kubernetes.io/name: node-exporter
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.service.port }}
      targetPort: metrics
