apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
